exclude_paths:
  - tmp
  - vendor

detectors:
  FeatureEnvy:
    exclude:
      - Terminus::Actions::API::Images::Create#handle
      - Terminus::Images::Greyscaler#convert
      - Terminus::Images::Screensaver#save
  LongParameterList:
    enabled: false
  TooManyStatements:
    exclude:
      - Terminus::Images::Greyscaler#convert
      - Terminus::Images::Screensaver#save
